### ISSUE TITLE
NPE in plug-in org.pdtextensions.semanticanalysis

### ISSUE THREAD

**Issue by tbl0605** [pdt-eg/Core-Plugin#113]
Hi,
Step to reproduce:
1. create a new PHP project and set PHP version to PHP 4
2. create a new PHP file containing PHP 5.6 code (containing a class with few methods)
3. switch many times the PHP project version from PHP4 to PHP 5.6 and back to PHP 4
4. after a certain time, you will see some error logs (see below)

Actually I think my project simply went corrupted after a certain time, so it's not a big issue, but I still wanted to report the problem ;)

The fix should be quite easy:
check that s.getParts() in UsageValidator#visit(UseStatement s) and s.getInterfaceList() in UsageValidator#visit(ClassDeclaration s) are not null before trying to iterate over them.
And so do probably the same with superClasses.getChilds() in UsageValidator#visit(InterfaceDeclaration s)...

----------------------------------------------------------------
First log :

java.lang.NullPointerException
	at org.pdtextensions.semanticanalysis.validation.validator.UsageValidator.visit(UsageValidator.java:181)
	at org.eclipse.php.internal.core.compiler.ast.visitor.PHPASTVisitor.visit(PHPASTVisitor.java:1400)
	at org.eclipse.dltk.ast.declarations.TypeDeclaration.traverse(TypeDeclaration.java:153)
	at org.eclipse.dltk.ast.statements.Block.traverse(Block.java:43)
	at org.eclipse.dltk.ast.declarations.ModuleDeclaration.traverse(ModuleDeclaration.java:71)
	at org.pdtextensions.semanticanalysis.validation.AbstractValidator.validate(AbstractValidator.java:31)
	at org.pdtextensions.semanticanalysis.validation.validator.UsageValidator.validate(UsageValidator.java:68)
	at org.pdtextensions.internal.semanticanalysis.integration.BuildParticipant.validate(BuildParticipant.java:102)
	at org.pdtextensions.internal.semanticanalysis.integration.BuildParticipant.build(BuildParticipant.java:72)
	at org.eclipse.dltk.internal.core.ReconcileBuilder.run(ReconcileBuilder.java:103)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.dltk.internal.core.ReconcileBuilder.build(ReconcileBuilder.java:81)
	at org.eclipse.dltk.internal.core.ReconcileWorkingCopyOperation.makeConsistent(ReconcileWorkingCopyOperation.java:91)
	at org.eclipse.dltk.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:58)
	at org.eclipse.dltk.internal.core.ModelOperation.run(ModelOperation.java:698)
	at org.eclipse.dltk.internal.core.ModelOperation.runOperation(ModelOperation.java:764)
	at org.eclipse.dltk.internal.core.SourceModule.reconcile(SourceModule.java:330)
	at org.eclipse.php.internal.ui.editor.validation.PhpReconcilingStrategy.reconcile(PhpReconcilingStrategy.java:152)
	at org.eclipse.php.internal.ui.editor.validation.PhpReconcilingStrategy.access$0(PhpReconcilingStrategy.java:138)
	at org.eclipse.php.internal.ui.editor.validation.PhpReconcilingStrategy$2.run(PhpReconcilingStrategy.java:221)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.php.internal.ui.editor.validation.PhpReconcilingStrategy.validate(PhpReconcilingStrategy.java:219)
	at org.eclipse.php.internal.ui.editor.validation.PhpReconcilingStrategy.validate(PhpReconcilingStrategy.java:195)
	at org.eclipse.wst.sse.ui.internal.reconcile.validator.ReconcileStepForValidator.validate(ReconcileStepForValidator.java:303)
	at org.eclipse.wst.sse.ui.internal.reconcile.validator.ReconcileStepForValidator.reconcileModel(ReconcileStepForValidator.java:262)
	at org.eclipse.jface.text.reconciler.AbstractReconcileStep.reconcile(AbstractReconcileStep.java:95)
	at org.eclipse.wst.sse.ui.internal.reconcile.validator.ValidatorStrategy.reconcile(ValidatorStrategy.java:269)
	at org.eclipse.wst.sse.ui.internal.reconcile.DocumentRegionProcessor.process(DocumentRegionProcessor.java:321)
	at org.eclipse.wst.sse.ui.internal.reconcile.StructuredRegionProcessor.process(StructuredRegionProcessor.java:258)
	at org.eclipse.wst.sse.ui.internal.reconcile.DirtyRegionProcessor$BackgroundThread.run(DirtyRegionProcessor.java:691)

----------------------------------------------------------------
Second log:

java.lang.NullPointerException
	at org.pdtextensions.semanticanalysis.validation.validator.ImplementationValidator.visit(ImplementationValidator.java:100)
	at org.eclipse.php.internal.core.compiler.ast.visitor.PHPASTVisitor.visit(PHPASTVisitor.java:1400)
	at org.eclipse.dltk.ast.declarations.TypeDeclaration.traverse(TypeDeclaration.java:153)
	at org.eclipse.dltk.ast.statements.Block.traverse(Block.java:43)
	at org.eclipse.dltk.ast.declarations.ModuleDeclaration.traverse(ModuleDeclaration.java:71)
	at org.pdtextensions.semanticanalysis.validation.AbstractValidator.validate(AbstractValidator.java:31)
	at org.pdtextensions.semanticanalysis.validation.validator.ImplementationValidator.validate(ImplementationValidator.java:222)
	at org.pdtextensions.internal.semanticanalysis.integration.BuildParticipant.validate(BuildParticipant.java:102)
	at org.pdtextensions.internal.semanticanalysis.integration.BuildParticipant.build(BuildParticipant.java:72)
	at org.eclipse.dltk.internal.core.ReconcileBuilder.run(ReconcileBuilder.java:103)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.dltk.internal.core.ReconcileBuilder.build(ReconcileBuilder.java:81)
	at org.eclipse.dltk.internal.core.ReconcileWorkingCopyOperation.makeConsistent(ReconcileWorkingCopyOperation.java:91)
	at org.eclipse.dltk.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:58)
	at org.eclipse.dltk.internal.core.ModelOperation.run(ModelOperation.java:698)
	at org.eclipse.dltk.internal.core.ModelOperation.runOperation(ModelOperation.java:764)
	at org.eclipse.dltk.internal.core.SourceModule.reconcile(SourceModule.java:330)
	at org.eclipse.php.internal.ui.editor.validation.PhpReconcilingStrategy.reconcile(PhpReconcilingStrategy.java:152)
	at org.eclipse.php.internal.ui.editor.validation.PhpReconcilingStrategy.access$0(PhpReconcilingStrategy.java:138)
	at org.eclipse.php.internal.ui.editor.validation.PhpReconcilingStrategy$2.run(PhpReconcilingStrategy.java:221)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.php.internal.ui.editor.validation.PhpReconcilingStrategy.validate(PhpReconcilingStrategy.java:219)
	at org.eclipse.php.internal.ui.editor.validation.PhpReconcilingStrategy.validate(PhpReconcilingStrategy.java:195)
	at org.eclipse.wst.sse.ui.internal.reconcile.validator.ReconcileStepForValidator.validate(ReconcileStepForValidator.java:303)
	at org.eclipse.wst.sse.ui.internal.reconcile.validator.ReconcileStepForValidator.reconcileModel(ReconcileStepForValidator.java:262)
	at org.eclipse.jface.text.reconciler.AbstractReconcileStep.reconcile(AbstractReconcileStep.java:95)
	at org.eclipse.wst.sse.ui.internal.reconcile.validator.ValidatorStrategy.reconcile(ValidatorStrategy.java:269)
	at org.eclipse.wst.sse.ui.internal.reconcile.DocumentRegionProcessor.process(DocumentRegionProcessor.java:321)
	at org.eclipse.wst.sse.ui.internal.reconcile.StructuredRegionProcessor.process(StructuredRegionProcessor.java:258)
	at org.eclipse.wst.sse.ui.internal.reconcile.DirtyRegionProcessor$BackgroundThread.run(DirtyRegionProcessor.java:691)

**Comment by zulus** [comment]
Thank you for these logs.
