### ISSUE TITLE
An internal error occurred during: "PHP CodeSniffer".

### ISSUE THREAD

**Issue by jfranciscos4** [pdt-eg/Core-Plugin#125]
null
org.eclipse.core.jobs
Error
Tue Jul 07 18:34:12 BRT 2015
An internal error occurred during: "PHP CodeSniffer".

java.lang.NoSuchMethodError: org.eclipse.php.internal.debug.core.preferences.PHPDebuggersRegistry.getDebuggerConfiguration(Ljava/lang/String;)Lorg/eclipse/php/internal/debug/core/debugger/AbstractDebuggerConfiguration;
	at org.phpsrc.eclipse.pti.core.launching.PHPToolLauncher.createConfiguration(PHPToolLauncher.java:376)
	at org.phpsrc.eclipse.pti.core.launching.PHPToolLauncher.findLaunchConfiguration(PHPToolLauncher.java:265)
	at org.phpsrc.eclipse.pti.core.launching.PHPToolLauncher.launch(PHPToolLauncher.java:136)
	at org.phpsrc.eclipse.pti.core.launching.PHPToolLauncher.launch(PHPToolLauncher.java:113)
	at org.phpsrc.eclipse.pti.tools.codesniffer.core.PHPCodeSniffer.launchFile(PHPCodeSniffer.java:121)
	at org.phpsrc.eclipse.pti.tools.codesniffer.core.PHPCodeSniffer.parse(PHPCodeSniffer.java:68)
	at org.phpsrc.eclipse.pti.tools.codesniffer.validator.PHPCodeSnifferValidator.validateFile(PHPCodeSnifferValidator.java:72)
	at org.phpsrc.eclipse.pti.tools.codesniffer.validator.PHPCodeSnifferValidator.validate(PHPCodeSnifferValidator.java:57)
	at org.phpsrc.eclipse.pti.tools.codesniffer.core.jobs.ValidationJob.validateFile(ValidationJob.java:83)
	at org.phpsrc.eclipse.pti.tools.codesniffer.core.jobs.ValidationJob.run(ValidationJob.java:52)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by zulus** [comment]
Fixed in latest PDT snapshot. See also https://bugs.eclipse.org/bugs/show_bug.cgi?id=473050
