### ISSUE TITLE
'For input string: "Class"' error spammed in Error Log for every class in every opened file

### ISSUE THREAD

**Issue by NobleUplift** [pdt-eg/Core-Plugin#134]
An example error:

Plug-in: org.eclipse.php.core
Message: For input string: "PDO"
Stack Trace:
```
java.lang.NumberFormatException: For input string: "PDO"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.eclipse.php.internal.core.index.PhpElementResolver.resolve(PhpElementResolver.java:49)
	at org.eclipse.dltk.core.index2.search.ModelAccess$1.match(ModelAccess.java:300)
	at org.eclipse.dltk.internal.core.index.sql.SqlSearchEngine$ElementHandler.match(SqlSearchEngine.java:314)
	at org.eclipse.dltk.internal.core.index.sql.SqlSearchEngine$ElementHandler.handle(SqlSearchEngine.java:295)
	at org.eclipse.dltk.internal.core.index.sql.h2.H2ElementDao.search(H2ElementDao.java:359)
	at org.eclipse.dltk.internal.core.index.sql.SqlSearchEngine.search(SqlSearchEngine.java:155)
	at org.eclipse.dltk.core.index2.search.ModelAccess.findElements(ModelAccess.java:310)
	at org.eclipse.dltk.core.index2.search.ModelAccess.findElements(ModelAccess.java:270)
	at org.eclipse.dltk.core.index2.search.ModelAccess.findElements(ModelAccess.java:263)
	at org.eclipse.dltk.core.index2.search.ModelAccess.findTypes(ModelAccess.java:203)
	at org.eclipse.php.internal.core.model.PhpModelAccess.findTypes(PhpModelAccess.java:148)
	at org.pdtextensions.core.util.PDTModelUtils.findTypes(PDTModelUtils.java:650)
	at org.pdtextensions.semanticanalysis.validation.validator.UsageValidator.isResolved(UsageValidator.java:349)
	at org.pdtextensions.semanticanalysis.validation.validator.UsageValidator.isResolved(UsageValidator.java:279)
	at org.pdtextensions.semanticanalysis.validation.validator.UsageValidator.visit(UsageValidator.java:165)
	at org.eclipse.php.internal.core.compiler.ast.visitor.PHPASTVisitor.visit(PHPASTVisitor.java:1094)
	at org.eclipse.php.internal.core.compiler.ast.visitor.PHPASTVisitor.visit(PHPASTVisitor.java:1345)
	at org.eclipse.php.internal.core.compiler.ast.nodes.FormalParameter.traverse(FormalParameter.java:72)
	at org.eclipse.dltk.ast.declarations.MethodDeclaration.traverseChildNodes(MethodDeclaration.java:91)
	at org.eclipse.dltk.ast.declarations.MethodDeclaration.traverse(MethodDeclaration.java:71)
	at org.eclipse.dltk.ast.statements.Block.traverse(Block.java:43)
	at org.eclipse.dltk.ast.declarations.TypeDeclaration.traverse(TypeDeclaration.java:158)
	at org.eclipse.dltk.ast.statements.Block.traverse(Block.java:43)
	at org.eclipse.dltk.ast.declarations.TypeDeclaration.traverse(TypeDeclaration.java:158)
	at org.eclipse.dltk.ast.statements.Block.traverse(Block.java:43)
	at org.eclipse.dltk.ast.declarations.ModuleDeclaration.traverse(ModuleDeclaration.java:71)
	at org.pdtextensions.semanticanalysis.validation.AbstractValidator.validate(AbstractValidator.java:31)
	at org.pdtextensions.semanticanalysis.validation.validator.UsageValidator.validate(UsageValidator.java:73)
	at org.pdtextensions.internal.semanticanalysis.integration.BuildParticipant.validate(BuildParticipant.java:102)
	at org.pdtextensions.internal.semanticanalysis.integration.BuildParticipant.build(BuildParticipant.java:72)
	at org.eclipse.dltk.internal.core.ReconcileBuilder.run(ReconcileBuilder.java:103)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.dltk.internal.core.ReconcileBuilder.build(ReconcileBuilder.java:81)
	at org.eclipse.dltk.internal.core.ReconcileWorkingCopyOperation.makeConsistent(ReconcileWorkingCopyOperation.java:91)
	at org.eclipse.dltk.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:58)
	at org.eclipse.dltk.internal.core.ModelOperation.run(ModelOperation.java:698)
	at org.eclipse.dltk.internal.core.ModelOperation.runOperation(ModelOperation.java:764)
	at org.eclipse.dltk.internal.core.SourceModule.reconcile(SourceModule.java:330)
	at org.eclipse.php.internal.ui.editor.validation.PhpReconcilingStrategy.reconcile(PhpReconcilingStrategy.java:148)
	at org.eclipse.php.internal.ui.editor.validation.PhpReconcilingStrategy.access$0(PhpReconcilingStrategy.java:136)
	at org.eclipse.php.internal.ui.editor.validation.PhpReconcilingStrategy$2.run(PhpReconcilingStrategy.java:211)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.php.internal.ui.editor.validation.PhpReconcilingStrategy.validate(PhpReconcilingStrategy.java:209)
	at org.eclipse.php.internal.ui.editor.validation.PhpReconcilingStrategy.validate(PhpReconcilingStrategy.java:187)
	at org.eclipse.wst.sse.ui.internal.reconcile.validator.ReconcileStepForValidator.validate(ReconcileStepForValidator.java:303)
	at org.eclipse.wst.sse.ui.internal.reconcile.validator.ReconcileStepForValidator.reconcileModel(ReconcileStepForValidator.java:262)
	at org.eclipse.jface.text.reconciler.AbstractReconcileStep.reconcile(AbstractReconcileStep.java:95)
	at org.eclipse.wst.sse.ui.internal.reconcile.validator.ValidatorStrategy.reconcile(ValidatorStrategy.java:269)
	at org.eclipse.wst.sse.ui.internal.reconcile.DocumentRegionProcessor.process(DocumentRegionProcessor.java:321)
	at org.eclipse.wst.sse.ui.internal.reconcile.StructuredRegionProcessor.process(StructuredRegionProcessor.java:258)
	at org.eclipse.wst.sse.ui.internal.reconcile.DirtyRegionProcessor$BackgroundThread.run(DirtyRegionProcessor.java:691)
```

I am on PHP Development Tools (PDT) 3.7.0.201601062353 org.eclipse.php.feature.group	Eclipse PDT, and trying to upgrade to PDT Extensions 0.22.1.201511050501 org.pdtextensions.feature.feature.group http://pdt-extensions.org.

Removing PDT Extensions got rid of this error.

Also occurring with   PDT Extensions 0.22.0.201510021218 org.pdtextensions.feature.feature.group	http://pdt-extensions.org.

The offending line can be located here:

https://github.com/eclipse/pdt/blob/master/plugins/org.eclipse.php.core/src/org/eclipse/php/internal/core/index/PhpElementResolver.java#L49

Called from here.

https://github.com/eclipse/dltk.core/blob/a3275c532b986f8beaed7782b888122fa4ab9edf/core/plugins/org.eclipse.dltk.core/index/org/eclipse/dltk/core/index2/search/ModelAccess.java#L300

**Comment by NobleUplift** [comment]
Does no one else have this issue?

**Comment by zulus** [comment]
Run Project -> Clean. If problem still exists, sample will be needed.

**Comment by zulus** [comment]
Any luck? Can I close this bug?

**Comment by NobleUplift** [comment]
I was still getting this last time I tried to clean my project and check my error log. I'll check now.

**Comment by zulus** [comment]
Or 

# close eclipse
# drop WORKSPACE_LOCATION/.metadata/.plugins/org.eclipse.dltk.core.index.sql.h2/ 
# start eclipse
# wait until build ends

**Comment by zulus** [comment]
Or please upload a sample. This is probably bug on PDT side.

**Comment by NobleUplift** [comment]
When I uninstall PDT Extensions this spam still completely disappears. I deleted the H2 DLTK index and it's working right now.

**Comment by NobleUplift** [comment]
Haven't received this error after two days so I'm considering it closed!!! Very happy right now. Typing \ doesn't freeze Eclipse for 5 seconds now either.
