### ISSUE TITLE
Bug with New Class wizard

### ISSUE THREAD

**Issue by gossi** [pdt-eg/Core-Plugin#146]
I do get the error, seen in this screenshot (I moved the error dialog down, so you can see what I put in the class wizard). Basically: It happens when I fill out the text-input for superclass.

<img width="527" alt="bildschirmfoto 2016-06-30 um 21 31 57" src="https://cloud.githubusercontent.com/assets/283700/16501685/ecf4464c-3f0a-11e6-8f03-98818d940e67.png">

Here is the stack trace:

```
java.lang.reflect.InvocationTargetException
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:398)
	at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:993)
	at org.eclipse.dltk.ui.wizards.NewElementWizard.performFinish(NewElementWizard.java:130)
	at org.eclipse.dltk.ui.wizards.NewSourceModuleWizard.performFinish(NewSourceModuleWizard.java:129)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:790)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:423)
	at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:618)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4248)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1501)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1509)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1313)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.eclipse.ui.internal.actions.NewWizardShortcutAction.run(NewWizardShortcutAction.java:133)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.jface.action.ActionContributionItem$$Lambda$36/1060790417.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4248)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1501)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1509)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1313)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
Caused by: java.lang.NoSuchMethodError: org.eclipse.php.internal.core.typeinference.PHPModelUtils.extractNameSapceName(Ljava/lang/String;)Ljava/lang/String;
	at org.pdtextensions.core.ui.codemanipulation.ElementStub.extractNamespaceName(ElementStub.java:83)
	at org.pdtextensions.core.ui.codemanipulation.ElementStub.getUseNamespaceString(ElementStub.java:75)
	at org.pdtextensions.core.ui.codemanipulation.ClassStub.getUseNamespacesList(ClassStub.java:187)
	at org.pdtextensions.core.ui.codemanipulation.ElementStub.generateNamespacePart(ElementStub.java:52)
	at org.pdtextensions.core.ui.codemanipulation.ClassStub.generateCode(ClassStub.java:69)
	at org.pdtextensions.core.ui.codemanipulation.ElementStub.toString(ElementStub.java:91)
	at org.pdtextensions.core.ui.wizards.NewClassWizardPage.generateFileContent(NewClassWizardPage.java:64)
	at org.pdtextensions.core.ui.wizards.NewElementWizardPage.getFileContent(NewElementWizardPage.java:603)
	at org.eclipse.dltk.ui.wizards.NewSourceModulePage$InitializeFileContent.execute(NewSourceModulePage.java:456)
	at org.eclipse.dltk.ui.wizards.NewSourceModulePage.createFile(NewSourceModulePage.java:497)
	at org.eclipse.dltk.ui.wizards.NewSourceModuleWizard.finishPage(NewSourceModuleWizard.java:124)
	at org.eclipse.dltk.ui.wizards.NewElementWizard$2.run(NewElementWizard.java:114)
	at org.eclipse.dltk.internal.core.BatchOperation.executeOperation(BatchOperation.java:37)
	at org.eclipse.dltk.internal.core.ModelOperation.run(ModelOperation.java:703)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.dltk.core.DLTKCore.run(DLTKCore.java:1431)
	at org.eclipse.dltk.internal.ui.actions.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:83)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Root exception:
java.lang.NoSuchMethodError: org.eclipse.php.internal.core.typeinference.PHPModelUtils.extractNameSapceName(Ljava/lang/String;)Ljava/lang/String;
	at org.pdtextensions.core.ui.codemanipulation.ElementStub.extractNamespaceName(ElementStub.java:83)
	at org.pdtextensions.core.ui.codemanipulation.ElementStub.getUseNamespaceString(ElementStub.java:75)
	at org.pdtextensions.core.ui.codemanipulation.ClassStub.getUseNamespacesList(ClassStub.java:187)
	at org.pdtextensions.core.ui.codemanipulation.ElementStub.generateNamespacePart(ElementStub.java:52)
	at org.pdtextensions.core.ui.codemanipulation.ClassStub.generateCode(ClassStub.java:69)
	at org.pdtextensions.core.ui.codemanipulation.ElementStub.toString(ElementStub.java:91)
	at org.pdtextensions.core.ui.wizards.NewClassWizardPage.generateFileContent(NewClassWizardPage.java:64)
	at org.pdtextensions.core.ui.wizards.NewElementWizardPage.getFileContent(NewElementWizardPage.java:603)
	at org.eclipse.dltk.ui.wizards.NewSourceModulePage$InitializeFileContent.execute(NewSourceModulePage.java:456)
	at org.eclipse.dltk.ui.wizards.NewSourceModulePage.createFile(NewSourceModulePage.java:497)
	at org.eclipse.dltk.ui.wizards.NewSourceModuleWizard.finishPage(NewSourceModuleWizard.java:124)
	at org.eclipse.dltk.ui.wizards.NewElementWizard$2.run(NewElementWizard.java:114)
	at org.eclipse.dltk.internal.core.BatchOperation.executeOperation(BatchOperation.java:37)
	at org.eclipse.dltk.internal.core.ModelOperation.run(ModelOperation.java:703)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.dltk.core.DLTKCore.run(DLTKCore.java:1431)
	at org.eclipse.dltk.internal.ui.actions.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:83)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
```

**Comment by zulus** [comment]
Works correctly with nightly.
