### ISSUE TITLE
Open PHP Type don't work

### ISSUE THREAD

**Issue by Mandos** [pdt-eg/Core-Plugin#58]
I don't know if it's problem  with PDT, PDT-E or DTLK but I after update to nightly version of this three Open PHP Type stop working. This is error log I get.

eclipse.buildId=4.3.0.I20130516-2200
java.version=1.7.0_17
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

Error
Wed May 29 11:34:39 CEST 2013
Background Indexer Crash Recovery

java.lang.NoClassDefFoundError: org/antlr/runtime/RecognizerSharedState
	at com.dubture.doctrine.annotation.parser.antlr.AnnotationLexer.<init>(AnnotationLexer.java:53)
	at com.dubture.doctrine.annotation.parser.AnnotationCommentParser.parseChunk(AnnotationCommentParser.java:327)
	at com.dubture.doctrine.annotation.parser.AnnotationCommentParser.parse(AnnotationCommentParser.java:240)
	at com.dubture.doctrine.core.index.DoctrineIndexingVisitorExtension.extractAnnotations(DoctrineIndexingVisitorExtension.java:165)
	at com.dubture.doctrine.core.index.DoctrineIndexingVisitorExtension.processClassDeclaration(DoctrineIndexingVisitorExtension.java:89)
	at com.dubture.doctrine.core.index.DoctrineIndexingVisitorExtension.visit(DoctrineIndexingVisitorExtension.java:79)
	at org.eclipse.php.internal.core.index.PhpIndexingVisitor.visit(PhpIndexingVisitor.java:408)
	at org.eclipse.dltk.ast.declarations.TypeDeclaration.traverse(TypeDeclaration.java:153)
	at org.eclipse.dltk.ast.statements.Block.traverse(Block.java:43)
	at org.eclipse.dltk.ast.declarations.ModuleDeclaration.traverse(ModuleDeclaration.java:71)
	at org.eclipse.php.internal.core.index.PhpIndexingParser.parseSourceModule(PhpIndexingParser.java:30)
	at org.eclipse.dltk.core.index2.AbstractIndexer.indexDocument(AbstractIndexer.java:45)
	at org.eclipse.dltk.internal.core.index.sql.SqlIndexer.indexDocument(SqlIndexer.java:147)
	at org.eclipse.dltk.internal.core.index2.SourceModulesRequest.run(SourceModulesRequest.java:78)
	at org.eclipse.dltk.core.search.indexing.AbstractJob.execute(AbstractJob.java:76)
	at org.eclipse.dltk.internal.core.search.processing.JobManager.run(JobManager.java:467)
	at java.lang.Thread.run(Thread.java:722)

**Comment by zulus** [comment]
I forced correct ANTLR version in latest build.
